In [1]:
##maltivariate regression.

#price=m1*area+m2*bedrooms+m3+age+b
#area,bedroom,age=independent variables(features)
#price=dependent variable
#b=constant

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df=pd.read_csv(r'E:\py\homeprices.csv')

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
#to add the misssing data
med=df.bedrooms.median()

In [8]:
med

4.0

In [11]:
df.bedrooms=df.bedrooms.fillna(med)

In [12]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
reg=linear_model.LinearRegression()

In [19]:
#we are passing 3 variables,we need to use 2 brackets so that there is no need of reshaping it.
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
reg.coef_
#m1,m2,m3

array([  112.06244194, 23388.88007794, -3231.71790863])

In [21]:
reg.intercept_
#b

221323.00186540408

In [23]:
reg.predict([[3000,3,15]])

array([579201.19929613])

In [24]:
112.06*3000+23388.88*3+(-3231.71*15)+221323.00

579193.99

In [25]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [26]:
#assignment:

df=pd.read_csv('E:\py\hiring.csv')

In [27]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [29]:
df.experience=df.experience.fillna('zero')

In [30]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [36]:
from word2number import w2n


In [40]:
#to convert to number from numeric string.
df.experience=df.experience.apply(w2n.word_to_num)

In [41]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [49]:
df=df.rename(columns={'test_score(out of 10)':'test_score','interview_score(out of 10)':'interview_score'})

In [50]:
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         NaN                7      72000
7          11         7.0                8      80000

In [52]:
med=df.test_score.median()
df.test_score=df.test_score.fillna(med)

In [53]:
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         8.0                7      72000
7          11         7.0                8      80000

In [56]:
reg=linear_model.LinearRegression()

In [64]:
df=df.rename(columns={'salary($)':'salary'})

In [65]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [66]:
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [68]:
reg.intercept_

17737.26346433771

In [69]:
reg.predict([[1,8,8]])

array([52957.7874818])